---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    type: master
    master: true
    node: true
    ipaddr: "{{ master1 }}"
  roles:
    - {role: 'ocp-rhv'}

- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
    ipaddr: "{{ node1 }}"
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-rhv'}

- hosts: all
  remote_user: root
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-quick'}
