---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
    ip_addr: "{{ node1 }}"
#  vars_files:
#    - '../main.yml'
  roles:
    - {role: 'ocp-vmware'}
  tasks: 
    - name: add master server to inventory
      add_host:
        hostname: "{{ master1 }}"
        ansible_ssh_user: root
        ansible_ssh_pass: "{{ cf_ssh_pass }}"
        groupname: master

- hosts: master
  remote_user: root
#  vars_files:
#    - '../main.yml'
  tasks:
    - name: add newnodes line
      lineinfile:
        dest: /etc/ansible/hosts
        state: present
        insertafter: '^nodes'
        line: 'new_nodes'

    - name: add newnodes block
      blockinfile:
        insertafter: EOF
        path: /etc/ansible/hosts
        content: |
          [new_nodes]
          192.168.2.33 
- hosts: all
  remote_user: root
#  vars_files:
#    - '../main.yml'
  roles:
    - {role: 'ocp-scaleup'}
